---

- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart sshd

- name: Disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart sshd

- name: Update apt package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade apt to the latest packages
  apt: upgrade=safe

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming
