version: "3"

services:
  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    image: knboard_production_django
    volumes:
      - "django-static:/app/static"
      - "/var/log/knboard:/var/log/knboard"
      - "./backend/settings:/app/settings"
    env_file:
      - "./.env"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: knboard_production_nginx
    ports:
      - "80:80"
    volumes:
      - "django-static:/usr/share/nginx/django-static"
      - "./production/nginx/nginx.conf:/etc/nginx/nginx.conf"

  postgres:
    image: postgres:11
    volumes:
      - "/var/lib/postgresql/knboard:/var/lib/postgresql/data"
    env_file:
      - "./.env"

volumes:
  django-static:
