---

- name: Deploy live branch
  connection: ssh
  gather_facts: false
  hosts: knboard
  vars:
    env_file: ../.env
    repo_folder: /srv/knboard/
    repo_name: rrebase/knboard
    repo_branch: add-ansible
    ansible_become: true
    ansible_become_user: root

  tasks:
    - name: Checkout repo
      git:
        repo: https://github.com/{{ repo_name }}.git
        accept_hostkey: yes
        dest: "{{ repo_folder }}"
        version: "{{ repo_branch }}"
        key_file: /root/.ssh/id_rsa

    - name: Copy .env file to remote
      copy:
        src: "{{ env_file }}"
        dest: "{{ repo_folder }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Run `docker-compose build`
      command:
        docker-compose up --build --detach
      args:
        chdir: "{{ repo_folder }}"
      register: output

    - debug:
        var: output
