---

- include: roles/common/tasks/checkout.yml

- name: Create init-letsencrypt from template
  template:
    src: templates/letsencrypt.sh
    dest: /srv/knboard/init-letsencrypt.sh
    mode: a+x

- name: Run init-letsencrypt.sh
  shell: /srv/knboard/init-letsencrypt.sh
